all: stack_example heap_example aliasing_example crash_example

stack_example: stack_example.c
	gcc -Wall -Wextra -Werror -pedantic -std=gnu89 -g stack_example.c -o stack_example

heap_example: heap_example.c
	gcc -Wall -Wextra -Werror -pedantic -std=gnu89 -g heap_example.c -o heap_example

aliasing_example: aliasing_example.c
	gcc -Wall -Wextra -Werror -pedantic -std=gnu89 -g aliasing_example.c -o aliasing_example

crash_example: crash_example.c
	gcc -Wall -Wextra -Werror -pedantic -std=gnu89 -g crash_example.c -o crash_example
